#!/usr/bin/env bash
# Ported from Sol-LTX-Infer scripts/run_ltx23_sglang_hq_kwl_1080p10s.sh @ 29d0d9e.
# Env mapping excerpt ported from scripts/run_ltx23_sglang_hq_1080p10s.sh @ 29d0d9e.
# Reference only: do not execute from this loop.

set -euo pipefail

# LTX HQ KWL wrapper entrypoint:
export SGLANG_HQ_VARIANT=kwl
# exec "$SCRIPT_DIR/run_ltx23_sglang_hq_1080p10s.sh" "$@"

# Full KWL flag bundle mirrored by efficiency.transforms.KWLFusions. Set these
# before the LTX runner to force the complete operator-fusion set.
export SGLANG_HQ_KWL_SHARE_BLOCK0_SELF_ATTN=1
export SGLANG_HQ_KWL_SHARE_GUIDANCE_PREFIX=1
export SGLANG_HQ_KWL_FUSED_QK_ROPE=1
export SGLANG_HQ_KWL_FUSED_RMS_ADALN=1
export SGLANG_HQ_KWL_FUSED_ADALN=1
export SGLANG_HQ_KWL_FUSED_QKNORM_ROPE=1
export SGLANG_HQ_KWL_FUSED_DUAL_MODULATE=1
export SGLANG_HQ_KWL_FUSED_CA_DUAL_MODULATE=1
export SGLANG_HQ_KWL_FUSED_ADA_VALUES_ALL=1
export SGLANG_HQ_KWL_FUSED_RESIDUAL_GATE=1
export SGLANG_HQ_KWL_FUSED_FFN_PROJ_IN_GELU=1
export SGLANG_HQ_KWL_COMPILE_GATE_TO_OUT=1
export SGLANG_HQ_KWL_FUSED_AUDIO_QKVG=1
export SGLANG_HQ_KWL_ENABLE_FUSED_QKNORM_ROPE=1
export SGLANG_HQ_KWL_COMPILE_TILED_VAE=1

# The LTX HQ runner maps the SGLANG_HQ_KWL_* controls into model-specific
# SGLANG_LTX2_* switches during enable_kwl_env/enable_kwl_experimental_env.
export SGLANG_LTX2_SHARE_BLOCK0_SELF_ATTN="${SGLANG_HQ_KWL_SHARE_BLOCK0_SELF_ATTN:-0}"
export SGLANG_LTX2_SHARE_GUIDANCE_PREFIX="${SGLANG_HQ_KWL_SHARE_GUIDANCE_PREFIX:-0}"
export SGLANG_LTX2_FUSED_QK_ROPE="${SGLANG_HQ_KWL_FUSED_QK_ROPE:-0}"
export SGLANG_LTX2_FUSED_RMS_ADALN="${SGLANG_HQ_KWL_FUSED_RMS_ADALN:-0}"
export SGLANG_LTX2_FUSED_ADALN="${SGLANG_HQ_KWL_FUSED_ADALN:-0}"
export SGLANG_LTX2_FUSED_QKNORM_ROPE="${SGLANG_HQ_KWL_FUSED_QKNORM_ROPE:-0}"
export SGLANG_LTX2_FUSED_DUAL_MODULATE="${SGLANG_HQ_KWL_FUSED_DUAL_MODULATE:-0}"
export SGLANG_LTX2_FUSED_CA_DUAL_MODULATE="${SGLANG_HQ_KWL_FUSED_CA_DUAL_MODULATE:-0}"
export SGLANG_LTX2_FUSED_ADA_VALUES_ALL="${SGLANG_HQ_KWL_FUSED_ADA_VALUES_ALL:-1}"
export SGLANG_LTX2_FUSED_RESIDUAL_GATE="${SGLANG_HQ_KWL_FUSED_RESIDUAL_GATE:-0}"
export SGLANG_LTX2_FUSED_FFN_PROJ_IN_GELU="${SGLANG_HQ_KWL_FUSED_FFN_PROJ_IN_GELU:-0}"
export SGLANG_LTX2_COMPILE_GATE_TO_OUT="${SGLANG_HQ_KWL_COMPILE_GATE_TO_OUT:-0}"
export SGLANG_LTX2_FUSED_AUDIO_QKVG="${SGLANG_HQ_KWL_FUSED_AUDIO_QKVG:-0}"
export SGLANG_ENABLE_FUSED_QKNORM_ROPE="${SGLANG_HQ_KWL_ENABLE_FUSED_QKNORM_ROPE:-0}"
export SGLANG_LTX2_COMPILE_TILED_VAE_DECODER="${SGLANG_HQ_KWL_COMPILE_TILED_VAE:-0}"
export SGLANG_LTX2_VAE_COMPILE_MODE="${SGLANG_LTX2_VAE_COMPILE_MODE:-max-autotune-no-cudagraphs}"
