#!/usr/bin/env bash
# Shared launch body for both Cosmos3-Super arms. Sourced by
# models/cosmos3/<variant>/scripts/run_cosmos3_gpu.sh AFTER that variant has
# sourced its own env.sh, so the two arms differ only by the technique env and
# never by the official config. A baseline that drifts from the optimized arm's
# sampling config stops being a control.
#
# Contract with the caller (launch.sh, generated by scripts/launch_config.py):
#   OUT_DIR             must be set; all artifacts land here
#   SOL_LTX_INFER_ROOT  checkout of Efficient-Large-Model/Sol-LTX-Infer holding
#                       the Cosmos3 runtime + its .conda/ltx23 env
#                       (reference-only; pinned commit in model.toml)
# The variant env must define COSMOS3_VARIANT and COSMOS3_ARM.
#
# This body reproduces the env contract of Sol-LTX-Infer
# scripts/cosmos/slurm_cosmos3_super.sh and then delegates to that repo's
# run_cosmos3_cache_matrix.sh with a single variant. The cache variant strings
# are parsed inside the runtime, so the driver stays upstream; what is vendored
# here is the official config and the arm selection.
set -euo pipefail

: "${OUT_DIR:?OUT_DIR must be set (launch.sh sets it)}"
: "${SOL_LTX_INFER_ROOT:?SOL_LTX_INFER_ROOT must be set (models/cosmos3.toml [env])}"
: "${COSMOS3_VARIANT:?variant env.sh must be sourced before this file}"

MODEL_DIR="${COSMOS3_MODEL_DIR:?COSMOS3_MODEL_DIR must be set by the variant shim}"

MODEL_REPO="${MODEL_REPO:-nvidia/Cosmos3-Super}"
PYTHON_BIN="${PYTHON_BIN:-$SOL_LTX_INFER_ROOT/.conda/ltx23/bin/python}"
NUM_GPUS="${NUM_GPUS:-4}"
NUM_FRAMES="${NUM_FRAMES:-189}"
SEED="${SEED:-42}"
WARMUP="${WARMUP:-true}"

PROMPT="${PROMPT:-$(cat "${PROMPT_FILE:-$MODEL_DIR/prompts/default.txt}")}"
NEGATIVE_PROMPT="${NEGATIVE_PROMPT:-$(cat "${NEGATIVE_PROMPT_FILE:-$MODEL_DIR/prompts/negative.txt}")}"

mkdir -p "$OUT_DIR/logs"
CACHE="${SGLANG_CACHE_ROOT:-$OUT_DIR/.cache}"
mkdir -p "$CACHE"/{huggingface,xdg,torch,triton,torchinductor,torch_extensions,cuda,sgl_diffusion} "$OUT_DIR/.tmp"
export HF_HOME="${HF_HOME:-$CACHE/huggingface}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-$HF_HOME/hub}"
export HF_HUB_ENABLE_HF_TRANSFER=0
export HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
export XDG_CACHE_HOME="$CACHE/xdg"
export TORCH_HOME="$CACHE/torch"
export TRITON_CACHE_DIR="$CACHE/triton"
export TORCHINDUCTOR_CACHE_DIR="$CACHE/torchinductor"
export TORCH_EXTENSIONS_DIR="$CACHE/torch_extensions"
export CUDA_CACHE_PATH="$CACHE/cuda"
export SGLANG_DIFFUSION_CACHE_ROOT="$CACHE/sgl_diffusion"
export TMPDIR="$OUT_DIR/.tmp"

SITE_NVIDIA="$SOL_LTX_INFER_ROOT/.conda/ltx23/lib/python3.12/site-packages/nvidia"
if [[ -d "$SITE_NVIDIA/cu13" ]]; then
  export CUDA_HOME="${CUDA_HOME:-$SITE_NVIDIA/cu13}"
  export PATH="$CUDA_HOME/bin:$PATH"
  export LD_LIBRARY_PATH="$CUDA_HOME/lib64:$CUDA_HOME/lib:${LD_LIBRARY_PATH:-}"
fi

# Resolve the local HF snapshot the runtime should load.
REPO_CACHE_DIR="$HF_HUB_CACHE/models--${MODEL_REPO/\//--}"
if [[ ! -f "$REPO_CACHE_DIR/refs/main" ]]; then
  echo "[error] no HF snapshot ref for $MODEL_REPO under $HF_HUB_CACHE" >&2
  exit 1
fi
HASH="$(cat "$REPO_CACHE_DIR/refs/main")"
LOCAL_SNAPSHOT="$REPO_CACHE_DIR/snapshots/$HASH"
if [[ ! -f "$LOCAL_SNAPSHOT/model_index.json" ]]; then
  echo "[error] model_index.json missing for $MODEL_REPO at $LOCAL_SNAPSHOT" >&2
  exit 1
fi

echo "[run] host=$(hostname) arm=$COSMOS3_ARM variant=$COSMOS3_VARIANT out=$OUT_DIR"
echo "[run] model=$MODEL_REPO gpus=$NUM_GPUS frames=$NUM_FRAMES snapshot=$LOCAL_SNAPSHOT"
nvidia-smi --query-gpu=name,memory.total --format=csv,noheader || true

# Record the resolved configuration next to the artifacts so a run can be
# audited without re-deriving the env.
"$PYTHON_BIN" - "$OUT_DIR" "$COSMOS3_ARM" "$COSMOS3_VARIANT" "$NUM_FRAMES" <<'PYCFG'
import json, os, sys
out_dir, arm, variant, num_frames = sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])
knobs = {k: v for k, v in os.environ.items() if k.startswith("SGLANG_COSMOS3_")}
cfg = {
    "arm": arm,
    "cache_variant": variant,
    "model": os.environ.get("MODEL_REPO", "nvidia/Cosmos3-Super"),
    "height": 720, "width": 1280, "num_frames": num_frames, "fps": 24,
    "num_inference_steps": 35,
    "guidance_scale": 6.0,
    "flow_shift": 10.0,
    "max_sequence_length": 4096,
    "seed": int(os.environ.get("SEED", "42") or 42),
    "num_gpus": int(os.environ.get("NUM_GPUS", "4") or 4),
    "warmup": os.environ.get("WARMUP", "true"),
    "technique_env": dict(sorted(knobs.items())),
}
with open(os.path.join(out_dir, "run_config.json"), "w") as fh:
    json.dump(cfg, fh, indent=2, sort_keys=False)
PYCFG

cd "$SOL_LTX_INFER_ROOT"
ROOT="$OUT_DIR" \
MODEL_SIZES=64b \
VARIANTS="$COSMOS3_VARIANT" \
PROMPT_COUNT=1 \
PROMPT_0="$PROMPT" \
NEGATIVE_PROMPT="$NEGATIVE_PROMPT" \
HEIGHT=720 WIDTH=1280 NUM_FRAMES="$NUM_FRAMES" FPS=24 \
NUM_INFERENCE_STEPS=35 GUIDANCE_SCALE=6.0 FLOW_SHIFT=10.0 MAX_SEQUENCE_LENGTH=4096 \
SEED="$SEED" \
PYTHON_BIN="$PYTHON_BIN" \
COSMOS3_64B_MODEL_PATH="$LOCAL_SNAPSHOT" \
DIT_CPU_OFFLOAD=false \
COSMOS3_64B_NUM_GPUS="$NUM_GPUS" \
WARMUP="$WARMUP" WARMUP_STEPS=1 \
FORCE="${FORCE:-1}" \
MAKE_COMPARE=0 \
ALLOW_PARTIAL=1 \
bash scripts/cosmos/run_cosmos3_cache_matrix.sh 2>&1 | tee "$OUT_DIR/run.log"
exit "${PIPESTATUS[0]}"
