#!/usr/bin/env bash
# run_script for the Cosmos3-Super BASELINE arm — official 64B 4-GPU inference,
# no acceleration. launch.sh (generated by launch_candidate.py) cd's to the
# runtime root, exports the model [env] + OUT_DIR, then calls this shim.
set -euo pipefail
VARIANT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"     # models/cosmos3/baseline
COSMOS3_MODEL_DIR="$(cd "$VARIANT_DIR/.." && pwd)"                 # models/cosmos3
export COSMOS3_MODEL_DIR
# shellcheck source=../env.sh
source "$VARIANT_DIR/env.sh"
# shellcheck source=../../run_cosmos3_common.sh
source "$COSMOS3_MODEL_DIR/run_cosmos3_common.sh"
