#!/usr/bin/env bash
# run_script for the LTX-2.3 OPTIMIZED arm — KWL fusion + stage-1 SCSP cache +
# stage-2 PISA sparse attention + NVFP4 video FFN + stage-2 token prune.
# launch.sh (generated by launch_transfeat.py) cd's to the runtime root, exports
# the model [env] + OUT_DIR, then calls this shim.
set -euo pipefail
VARIANT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # models/ltx23/optimized
LTX23_MODEL_DIR="$(cd "$VARIANT_DIR/.." && pwd)"                 # models/ltx23
export LTX23_MODEL_DIR
# shellcheck source=../env.sh
source "$VARIANT_DIR/env.sh"
# shellcheck source=../../run_ltx23_common.sh
source "$LTX23_MODEL_DIR/run_ltx23_common.sh"
