#!/usr/bin/env bash
# Shared launch body for both LTX-2.3 arms. Sourced by
# models/ltx23/<variant>/scripts/run_ltx23_gpu.sh AFTER that variant has sourced
# its own env.sh, so the two arms differ only by the technique env and never by
# the official config or the CLI invocation. Keeping one body is deliberate: a
# baseline that drifts from the optimized arm's sampling config stops being a
# control.
#
# Contract with the caller (launch.sh, generated by scripts/launch_candidate.py):
#   OUT_DIR             must be set; all artifacts land here
#   SOL_LTX_INFER_ROOT  checkout of Efficient-Large-Model/Sol-LTX-Infer holding
#                       the 22B runtime + its .conda/ltx23 env (reference-only,
#                       never copied; pinned commit in models/ltx23/model.toml)
# The variant env must define LTX23_VARIANT, LTX23_CACHE_ALGO,
# LTX23_COMPONENT_ATTENTION_BACKENDS and LTX23_ATTENTION_BACKEND_CONFIG.
set -euo pipefail

: "${OUT_DIR:?OUT_DIR must be set (launch.sh sets it)}"
: "${SOL_LTX_INFER_ROOT:?SOL_LTX_INFER_ROOT must be set (models/ltx23.toml [env])}"
: "${LTX23_VARIANT:?variant env.sh must be sourced before this file}"

MODEL_DIR="${LTX23_MODEL_DIR:?LTX23_MODEL_DIR must be set by the variant shim}"

PYTHON_BIN="${PYTHON_BIN:-$SOL_LTX_INFER_ROOT/.conda/ltx23/bin/python}"
MODEL_PATH="${MODEL_PATH:-$SOL_LTX_INFER_ROOT/outputs/.cache/sgl_diffusion/materialized_models/Lightricks__LTX-2.3-c24cea94ab17c493}"
OFFICIAL_MODEL_DIR="${OFFICIAL_MODEL_DIR:-$SOL_LTX_INFER_ROOT/outputs/LTX-2.3-official-files}"
# distilled LoRA: prefer the -1.1 filename, fall back to the un-suffixed one
# (different HF snapshots ship one or the other).
if [[ -z "${DISTILLED_LORA:-}" ]]; then
  DISTILLED_LORA="$OFFICIAL_MODEL_DIR/ltx-2.3-22b-distilled-lora-384-1.1.safetensors"
  [[ -e "$DISTILLED_LORA" ]] || DISTILLED_LORA="$OFFICIAL_MODEL_DIR/ltx-2.3-22b-distilled-lora-384.safetensors"
fi
SPATIAL_UPSAMPLER="${SPATIAL_UPSAMPLER:-$MODEL_PATH/ltx-2.3-spatial-upscaler-x2-1.1.safetensors}"

PROMPT="${PROMPT:-$(cat "${PROMPT_FILE:-$MODEL_DIR/prompts/default.txt}")}"
NEGATIVE_PROMPT="${NEGATIVE_PROMPT:-$(cat "${NEGATIVE_PROMPT_FILE:-$MODEL_DIR/prompts/negative.txt}")}"
SEED="${SEED:-42}"
MASTER_PORT="${MASTER_PORT:-30005}"
PERFORMANCE_MODE="${PERFORMANCE_MODE:-speed}"
TWO_STAGE_DEVICE_MODE="${TWO_STAGE_DEVICE_MODE:-resident}"
export PERFORMANCE_MODE TWO_STAGE_DEVICE_MODE
# Warmup defaults ON: the optimized arm pays a one-time torch.compile/autotune
# cost on the first forward. Without a warmup pass that lands inside the timed
# window and the measured speedup reads far below steady state. Leave it on for
# any run that will be compared against the baseline.
WARMUP="${WARMUP:-true}"
WARMUP_STEPS="${WARMUP_STEPS:-1}"
export SGLANG_LTX2_DISTILLED_LORA_STRENGTH_STAGE_1="${SGLANG_LTX2_DISTILLED_LORA_STRENGTH_STAGE_1:-0.25}"
export SGLANG_LTX2_DISTILLED_LORA_STRENGTH_STAGE_2="${SGLANG_LTX2_DISTILLED_LORA_STRENGTH_STAGE_2:-0.5}"

mkdir -p "$OUT_DIR"
CACHE="${SGLANG_CACHE_ROOT:-$OUT_DIR/.cache}"
mkdir -p "$CACHE"/{huggingface,xdg,torch,triton,torchinductor,torch_extensions,cuda,sgl_diffusion} "$OUT_DIR/.tmp"
export HF_HOME="${HF_HOME:-$CACHE/huggingface}"
export HF_HUB_CACHE="${HF_HUB_CACHE:-$HF_HOME/hub}"
export XDG_CACHE_HOME="$CACHE/xdg"
export TORCH_HOME="$CACHE/torch"
export TRITON_CACHE_DIR="$CACHE/triton"
export TORCHINDUCTOR_CACHE_DIR="$CACHE/torchinductor"
export TORCH_EXTENSIONS_DIR="$CACHE/torch_extensions"
export CUDA_CACHE_PATH="$CACHE/cuda"
export CUDA_CACHE_MAXSIZE="${CUDA_CACHE_MAXSIZE:-4294967296}"
export SGLANG_DIFFUSION_CACHE_ROOT="$CACHE/sgl_diffusion"
export TMPDIR="$OUT_DIR/.tmp"
export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PYTHONUNBUFFERED=1
export PYTHONPATH="$SOL_LTX_INFER_ROOT/python:${PYTHONPATH:-}"

SITE_NVIDIA="$SOL_LTX_INFER_ROOT/.conda/ltx23/lib/python3.12/site-packages/nvidia"
if [[ -d "$SITE_NVIDIA/cu13" ]]; then
  export CUDA_HOME="$SITE_NVIDIA/cu13"
  export CUDA_PATH="$CUDA_HOME"
  export PATH="$CUDA_HOME/bin:${PATH:-}"
  export LD_LIBRARY_PATH="$SITE_NVIDIA/cublas/lib:$SITE_NVIDIA/cudnn/lib:$SITE_NVIDIA/nccl/lib:$CUDA_HOME/lib:$CUDA_HOME/lib64:${LD_LIBRARY_PATH:-}"
fi

required_assets=("$PYTHON_BIN" "$DISTILLED_LORA" "$SPATIAL_UPSAMPLER")
# When MODEL_PATH is an HF repo id rather than a materialized dir, let the
# runtime resolve it instead of demanding a local model_index.json.
[[ -d "$MODEL_PATH" ]] && required_assets+=("$MODEL_PATH/model_index.json")
for required in "${required_assets[@]}"; do
  if [[ ! -e "$required" ]]; then
    echo "[error] missing required LTX-2.3 asset: $required" >&2
    exit 1
  fi
done

EXTRA_ARGS=()
[[ -n "$LTX23_COMPONENT_ATTENTION_BACKENDS" ]] && EXTRA_ARGS+=(--component-attention-backends "$LTX23_COMPONENT_ATTENTION_BACKENDS")
[[ -n "$LTX23_ATTENTION_BACKEND_CONFIG" ]] && EXTRA_ARGS+=(--attention-backend-config "$LTX23_ATTENTION_BACKEND_CONFIG")

echo "[run] host=$(hostname) variant=$LTX23_VARIANT cache_algo=$LTX23_CACHE_ALGO out=$OUT_DIR"
echo "[run] sol_ltx_infer=$SOL_LTX_INFER_ROOT model=$MODEL_PATH"
nvidia-smi -L || true

# Record the resolved configuration next to the artifacts so a run can be
# audited without re-deriving the env.
"$PYTHON_BIN" - "$OUT_DIR" "$LTX23_VARIANT" "$LTX23_CACHE_ALGO" <<'PYCFG'
import json, os, sys
out_dir, variant, cache_algo = sys.argv[1], sys.argv[2], sys.argv[3]
knobs = {k: v for k, v in os.environ.items()
         if k.startswith(("SGLANG_LTX2_", "SGLANG_PIECEWISE_ATTN_", "SGLANG_ENABLE_"))}
cfg = {
    "variant": variant,
    "cache_algo": cache_algo,
    "pipeline_class_name": "LTX2TwoStageHQPipeline",
    "height": 1088, "width": 1920, "num_frames": 241, "fps": 24,
    "stage1_steps": 15, "stage1_sampler": "res2s",
    "stage2_sigmas": [0.909375, 0.725, 0.421875, 0.0],
    "stage2_steps": 3, "stage2_sampler": "res2s",
    "guidance_scale": 3.0,
    "seed": int(os.environ.get("SEED", "42") or 42),
    "num_gpus": 1,
    "warmup": os.environ.get("WARMUP", "true"),
    "stage1_lora_strength": float(os.environ.get("SGLANG_LTX2_DISTILLED_LORA_STRENGTH_STAGE_1", "0.25")),
    "stage2_lora_strength": float(os.environ.get("SGLANG_LTX2_DISTILLED_LORA_STRENGTH_STAGE_2", "0.5")),
    "technique_env": dict(sorted(knobs.items())),
}
with open(os.path.join(out_dir, "run_config.json"), "w") as fh:
    json.dump(cfg, fh, indent=2, sort_keys=False)
PYCFG

"$PYTHON_BIN" -m sglang.multimodal_gen.runtime.entrypoints.cli.main generate \
  --model-path "$MODEL_PATH" \
  --backend auto \
  "${EXTRA_ARGS[@]}" \
  --pipeline-class-name LTX2TwoStageHQPipeline \
  --component-paths.spatial_upsampler "$SPATIAL_UPSAMPLER" \
  --component-paths.distilled_lora "$DISTILLED_LORA" \
  --num-gpus 1 \
  --master-port "$MASTER_PORT" \
  --performance-mode "$PERFORMANCE_MODE" \
  --ltx2-two-stage-device-mode "$TWO_STAGE_DEVICE_MODE" \
  --warmup "$WARMUP" --warmup-steps "$WARMUP_STEPS" \
  --height 1088 --width 1920 --num-frames 241 --fps 24 --seed "$SEED" \
  --num-inference-steps 15 --guidance-scale 3.0 \
  --negative-prompt "$NEGATIVE_PROMPT" \
  --prompt "$PROMPT" \
  --output-file-path "$OUT_DIR/out.mp4" \
  --perf-dump-path "$OUT_DIR/perf.json" \
  --return-file-paths-only true 2>&1 | tee "$OUT_DIR/run.log"
exit "${PIPESTATUS[0]}"
