#!/usr/bin/env bash
# run_script for the Cosmos3-Super OPTIMIZED arm — TeaCache 1.15/start10/max3 +
# step-selective NVFP4. launch.sh (generated by launch_candidate.py) cd's to the
# runtime root, exports the model [env] + OUT_DIR, then calls this shim.
set -euo pipefail
VARIANT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"     # models/cosmos3/optimized
COSMOS3_MODEL_DIR="$(cd "$VARIANT_DIR/.." && pwd)"                 # models/cosmos3
export COSMOS3_MODEL_DIR
# shellcheck source=../env.sh
source "$VARIANT_DIR/env.sh"
# shellcheck source=../../run_cosmos3_common.sh
source "$COSMOS3_MODEL_DIR/run_cosmos3_common.sh"
