#!/usr/bin/env bash
# run_script for the LTX-2.3 BASELINE arm — official two-stage, no acceleration.
# launch.sh (generated by launch_candidate.py) cd's to the runtime root, exports
# the model [env] + OUT_DIR, then calls this shim.
set -euo pipefail
VARIANT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # models/ltx23/baseline
LTX23_MODEL_DIR="$(cd "$VARIANT_DIR/.." && pwd)"                 # models/ltx23
export LTX23_MODEL_DIR
# shellcheck source=../env.sh
source "$VARIANT_DIR/env.sh"
# shellcheck source=../../run_ltx23_common.sh
source "$LTX23_MODEL_DIR/run_ltx23_common.sh"
